url: "https://challenge2024.isic-archive.com/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ISIC 2024 Challenge Dataset" # the name of your site, e.g. ACME Corp.

github_username: imagemarkup
google_analytics: G-FLS85FF99P

email: support@isic-archive.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the landing page for the ISIC 2024 Challenge Dataset

postcss:
  cache: false

defaults:
  - scope:
      path: ""
    values:
      toc: false
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      permalink: /:categories/:title/
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      permalink: /:title/
collections:
  pages:
    output: true
    sort_by: order

exclude:
  - package.json
  - Makefile
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
